---
title: "Santa Clara County COVID-19 Analysis"
author: "David Jackson"
date: "11/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RSQLite)
library(ggplot2)
library(scales)
library(dplyr)

```

### COVID-19 Analysis for Santa Clara County CA.


```{r}
rm(list=ls())
source("../DATA/movavg.R")
db <- db <- dbConnect(RSQLite::SQLite(),dbname= "../COVIDDB/COVID.sqlite3")
df <- dbGetQuery(db,"select date,county,new_cases,new_deaths from COUNTYDAILY")
df <- subset(df,county=="Santa Clara"  )
df$date <- as.Date(df$date)
mean(df$new_cases)
mean(df$new_deaths)
```

#### Daily Mortality Rate

```{r}
df$Rate <- df$new_deaths/df$new_cases
mean(is.na(df$Rate))
df %>% filter(date >="2020-03-01") %>%
ggplot() + geom_line(aes(x=date,y=Rate)) +
  labs(title="Santa Clara County Mortality Rate by Date ") +
  scale_y_continuous(labels = percent) +
  geom_hline(yintercept =mean(is.na(df$Rate)),col="red" ) +
  scale_x_date()
```


### Plot of Daily new_cases and new_deaths

```{r}
ggplot(df) + geom_line(aes(x=date,y=new_cases,col="Daily new_cases")) +
  labs(title="COVID-19 new_cases by Date") +
  geom_smooth(aes(x=date,y=new_cases,col="Loess"),span=0.25) +
   scale_x_date()
  
```
```{r}
ggplot(df) + geom_line(aes(x=date,y=new_deaths,col="Daily new_deaths")) +
  labs(title="COVID-19 new_deaths by Date") + ylim(0,175) +
  geom_smooth(aes(x=date,y=new_deaths,col="Loess"),span=0.25) +
   scale_x_date()
```
```{r}
dfA <- subset(df,date >="2020-06-01")
ggplot(dfA) + geom_line(aes(x=date,y=new_cases,col="Daily new_cases")) +
  labs(title="COVID-19 new_cases by Date (since Jun. 1, 2020)") +
  geom_smooth(aes(x=date,y=new_cases,col="Loess"),span=0.25) +
   scale_x_date()

ggplot(dfA) + geom_line(aes(x=date,y=new_deaths,col="Daily new_deaths")) +
  labs(title="COVID-19 new_deaths by Date (since Jun. 1, 2020)") + ylim(0,175) +
  geom_smooth(aes(x=date,y=new_deaths,col="Loess"),span=0.25) +
   scale_x_date()
```

#### Non-Moving Average By Week and By Month

```{r}
df$Monthly <- as.Date(cut(df$date,
  breaks = "month"))
df$Weekly <- as.Date(cut(df$date,
  breaks = "week",
  start.on.monday = FALSE))

```
```{r}
Weekly_new_cases <- aggregate(new_cases~Weekly,df,FUN=sum)
Weekly_new_deaths <- aggregate(new_deaths~Weekly,df,FUN=sum)
Weekly_new_cases$DRate <- Weekly_new_deaths$new_deaths/Weekly_new_cases$new_cases
Weekly_new_cases$LivedSaved <- Weekly_new_cases$new_cases * (max(Weekly_new_cases$DRate) - Weekly_new_cases$DRate) * 100

```
```{r}
ggplot(Weekly_new_cases) + geom_col(aes(x=Weekly,y=new_cases)) + 
  labs(title="Weekly new_cases",x="Date date", y="Weekly new_cases")

ggplot(Weekly_new_deaths) + geom_col(aes(x=Weekly,y=new_deaths)) + 
  labs(title="Weekly new_deaths",x="Date date", y="Weekly new_deaths") +
   ylim(0,100)
```

#### Monthly new_cases and new_deaths

```{r}

Monthly_new_cases <- aggregate(new_cases~Monthly,df,FUN=sum)
Monthly_new_deaths <- aggregate(new_deaths~Monthly,df,FUN=sum)
Monthly_new_cases$DRate <- Monthly_new_deaths$new_deaths/Monthly_new_cases$new_cases
Monthly_new_cases$LivedSaved <- Monthly_new_cases$new_cases * (max(Monthly_new_cases$DRate) - Monthly_new_cases$DRate) * 100
```
```{r}
ggplot(Monthly_new_cases) + geom_col(aes(x=Monthly,y=new_cases)) +
  labs(title="Monthly new_cases")  +
  scale_y_continuous(labels=scales::comma)

ggplot(Monthly_new_deaths) + geom_col(aes(x=Monthly,y=new_deaths)) +
  labs(title="Monthly new_deaths")
```